# Generated by Django 4.1.4 on 2023-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('marks', models.FloatField(max_length=50)),
                ('image_url', models.CharField(max_length=2556)),
            ],
        ),
    ]
